import json
import re
from collections.abc import Callable
from collections import Counter
from typing import Any

from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
from pptx.util import Inches, Pt
from sqlmodel import Session

from backend.app.core.config import Settings
from backend.app.schemas.artifact import ArtifactRef, ArtifactType
from backend.app.schemas.physician import PhysicianRead
from backend.app.services.artifacts import finalize_artifact_file, register_artifact, to_artifact_ref
from backend.app.services.prompts import load_prompt


ACCENT = RGBColor(31, 78, 121)
TEXT = RGBColor(39, 45, 52)
MUTED = RGBColor(95, 108, 122)
LIGHT_FILL = RGBColor(234, 242, 248)
TextGenerator = Callable[[list[dict[str, object]]], str]


def generate_ppt_deck(
    *,
    session: Session,
    settings: Settings,
    generate_text: TextGenerator,
    topic: str,
    physicians: list[PhysicianRead],
    icd10_codes: list[str],
    slide_count: int,
    style_notes: str | None = None,
    artifact_provenance: dict[str, object] | None = None,
) -> ArtifactRef:
    plan = _build_deck_plan(
        generate_text=generate_text,
        topic=topic,
        physicians=physicians,
        icd10_codes=icd10_codes,
        slide_count=slide_count,
        style_notes=style_notes,
    )
    filename = f"{_slugify(topic or 'physician_summary')}.pptx"
    artifact, path = register_artifact(
        session,
        settings=settings,
        artifact_type=ArtifactType.pptx,
        filename=filename,
        source_agent="ppt",
        **_with_plan(artifact_provenance, plan),
    )

    deck = Presentation()
    deck.slide_width = Inches(13.333)
    deck.slide_height = Inches(7.5)

    _add_title_slide(deck, str(plan["title"]), str(plan["subtitle"]), physicians, icd10_codes)
    _add_overview_slide(deck, physicians)
    _add_insights_slide(deck, physicians, icd10_codes, _string_list(plan["insightBullets"]))
    _add_top_physicians_slide(deck, physicians)

    path.parent.mkdir(parents=True, exist_ok=True)
    deck.save(path)
    finalize_artifact_file(session, artifact, path)
    return to_artifact_ref(artifact)


def _add_title_slide(
    deck: Presentation,
    topic: str,
    subtitle: str,
    physicians: list[PhysicianRead],
    icd10_codes: list[str],
) -> None:
    slide = deck.slides.add_slide(deck.slide_layouts[6])
    _add_title(slide, topic or "Physician Landscape Summary", top=0.85, font_size=34)

    states = _top_labels([physician.state for physician in physicians], limit=6)
    scope = " | ".join(
        value
        for value in [
            f"{len(physicians)} filtered physicians",
            f"ICD-10: {', '.join(icd10_codes)}" if icd10_codes else "All NSCLC ICD-10 codes",
            f"Geography: {', '.join(states)}" if states else None,
        ]
        if value
    )
    _add_textbox(slide, scope, left=0.85, top=2.0, width=11.4, height=0.5, font_size=16, color=MUTED)
    if subtitle:
        _add_textbox(slide, subtitle, left=0.85, top=2.65, width=11.4, height=0.75, font_size=14, color=TEXT)
    _add_textbox(
        slide,
        "Generated by the DocNexus multi-agent orchestration workflow",
        left=0.85,
        top=6.55,
        width=11.4,
        height=0.35,
        font_size=11,
        color=MUTED,
    )
    _add_accent_bar(slide)


def _add_overview_slide(deck: Presentation, physicians: list[PhysicianRead]) -> None:
    slide = deck.slides.add_slide(deck.slide_layouts[6])
    _add_title(slide, "Physician Population Overview")
    _add_metric(slide, "Physicians", str(len(physicians)), 0.8)
    _add_metric(slide, "Total NSCLC Claims", str(sum(p.totalNSCLCClaims for p in physicians)), 3.7)
    _add_metric(slide, "Very High Volume", str(sum(1 for p in physicians if p.volumeTier == "very_high")), 6.9)

    specialties = Counter(physician.specialty for physician in physicians)
    states = Counter(physician.state for physician in physicians)
    _add_ranked_list(slide, "Top Specialties", specialties, left=0.95, top=3.05)
    _add_ranked_list(slide, "Top States", states, left=6.9, top=3.05)


def _add_insights_slide(
    deck: Presentation,
    physicians: list[PhysicianRead],
    icd10_codes: list[str],
    planned_insights: list[str],
) -> None:
    slide = deck.slides.add_slide(deck.slide_layouts[6])
    _add_title(slide, "Key Insights")

    insights = planned_insights or _build_insights(physicians, icd10_codes)
    top = 1.55
    for insight in insights:
        _add_bullet(slide, insight, top=top)
        top += 0.82


def _add_top_physicians_slide(deck: Presentation, physicians: list[PhysicianRead]) -> None:
    slide = deck.slides.add_slide(deck.slide_layouts[6])
    _add_title(slide, "Top 10 Physicians By NSCLC Claim Volume")

    top_physicians = sorted(physicians, key=lambda physician: physician.totalNSCLCClaims, reverse=True)[:10]
    table_shape = slide.shapes.add_table(
        rows=len(top_physicians) + 1,
        cols=5,
        left=Inches(0.55),
        top=Inches(1.35),
        width=Inches(12.25),
        height=Inches(5.55),
    )
    table = table_shape.table
    headers = ["Physician", "Specialty", "State", "Affiliation", "Claims"]
    widths = [2.15, 2.4, 0.7, 5.2, 0.95]
    for idx, width in enumerate(widths):
        table.columns[idx].width = Inches(width)

    for col, header in enumerate(headers):
        cell = table.cell(0, col)
        cell.text = header
        _style_cell(cell, is_header=True)

    for row, physician in enumerate(top_physicians, start=1):
        values = [
            f"{physician.firstName} {physician.lastName}",
            physician.specialty,
            physician.state,
            physician.affiliation,
            str(physician.totalNSCLCClaims),
        ]
        for col, value in enumerate(values):
            cell = table.cell(row, col)
            cell.text = value
            _style_cell(cell, is_header=False)


def _build_insights(physicians: list[PhysicianRead], icd10_codes: list[str]) -> list[str]:
    if not physicians:
        return ["No physicians matched the current filters; broaden geography, specialty, or volume tier."]

    states = Counter(physician.state for physician in physicians)
    specialties = Counter(physician.specialty for physician in physicians)
    total_claims = sum(physician.totalNSCLCClaims for physician in physicians)
    very_high = [physician for physician in physicians if physician.volumeTier == "very_high"]
    top_state, top_state_count = states.most_common(1)[0]
    top_specialty, top_specialty_count = specialties.most_common(1)[0]
    top_physician = max(physicians, key=lambda physician: physician.totalNSCLCClaims)

    insights = [
        f"The filtered cohort includes {len(physicians)} physicians and {total_claims} total NSCLC claims.",
        f"{top_state} has the largest physician count in scope ({top_state_count} physicians).",
        f"{top_specialty} is the leading specialty represented ({top_specialty_count} physicians).",
        f"{len(very_high)} physicians are classified as very high volume, indicating priority engagement opportunities.",
        f"{top_physician.firstName} {top_physician.lastName} leads the cohort with {top_physician.totalNSCLCClaims} NSCLC claims.",
    ]
    if icd10_codes:
        insights[0] += f" ICD-10 scope: {', '.join(icd10_codes)}."
    return insights


def _build_deck_plan(
    *,
    generate_text: TextGenerator,
    topic: str,
    physicians: list[PhysicianRead],
    icd10_codes: list[str],
    slide_count: int,
    style_notes: str | None,
) -> dict[str, Any]:
    fallback = _fallback_deck_plan(topic, physicians, icd10_codes)
    messages: list[dict[str, object]] = [
        {"role": "system", "content": load_prompt("ppt_agent.md")},
        {
            "role": "user",
            "content": json.dumps(
                {
                    "topic": topic,
                    "slideCount": slide_count,
                    "styleNotes": style_notes,
                    "icd10Codes": icd10_codes,
                    "physicianCount": len(physicians),
                    "physicians": [physician.model_dump(by_alias=True) for physician in physicians],
                    "requiredOutput": {
                        "title": "Deck title",
                        "subtitle": "One-sentence scope summary",
                        "insightBullets": "3-5 bullets grounded in supplied physician data",
                        "tableRationale": "Why these top physicians matter",
                    },
                }
            ),
        },
    ]
    try:
        raw_plan = json.loads(_strip_code_fences(generate_text(messages)))
    except Exception:
        return fallback
    if not isinstance(raw_plan, dict):
        return fallback

    title = str(raw_plan.get("title") or fallback["title"])[:140]
    subtitle = str(raw_plan.get("subtitle") or fallback["subtitle"])[:220]
    insights = _string_list(raw_plan.get("insightBullets"))[:5]
    if len(insights) < 3:
        insights = fallback["insightBullets"]
    return {
        "title": title,
        "subtitle": subtitle,
        "insightBullets": insights,
        "tableRationale": str(raw_plan.get("tableRationale") or fallback["tableRationale"])[:240],
    }


def _fallback_deck_plan(topic: str, physicians: list[PhysicianRead], icd10_codes: list[str]) -> dict[str, Any]:
    states = _top_labels([physician.state for physician in physicians], limit=4)
    return {
        "title": topic or "Physician Landscape Summary",
        "subtitle": (
            f"{len(physicians)} physicians"
            f" across {', '.join(states)}"
            f" for ICD-10 {', '.join(icd10_codes)}"
        ).strip(),
        "insightBullets": _build_insights(physicians, icd10_codes)[:5],
        "tableRationale": "Top physicians are ranked by total NSCLC claim volume.",
    }


def _with_plan(
    artifact_provenance: dict[str, object] | None,
    plan: dict[str, Any],
) -> dict[str, object]:
    updated = dict(artifact_provenance or {})
    provenance = dict(updated.get("provenance") or {})
    provenance["llmPlan"] = plan
    updated["provenance"] = provenance
    return updated


def _string_list(value: object) -> list[str]:
    if not isinstance(value, list):
        return []
    return [str(item).strip() for item in value if str(item).strip()]


def _strip_code_fences(text: str) -> str:
    stripped = text.strip()
    if stripped.startswith("```"):
        lines = stripped.splitlines()
        if lines and lines[0].startswith("```"):
            lines = lines[1:]
        if lines and lines[-1].startswith("```"):
            lines = lines[:-1]
        return "\n".join(lines)
    return stripped


def _add_title(slide, text: str, *, top: float = 0.45, font_size: int = 25) -> None:
    box = slide.shapes.add_textbox(Inches(0.65), Inches(top), Inches(12), Inches(0.55))
    frame = box.text_frame
    frame.clear()
    paragraph = frame.paragraphs[0]
    run = paragraph.add_run()
    run.text = text
    run.font.size = Pt(font_size)
    run.font.bold = True
    run.font.color.rgb = ACCENT


def _add_textbox(slide, text: str, *, left: float, top: float, width: float, height: float, font_size: int, color) -> None:
    box = slide.shapes.add_textbox(Inches(left), Inches(top), Inches(width), Inches(height))
    frame = box.text_frame
    frame.word_wrap = True
    frame.clear()
    paragraph = frame.paragraphs[0]
    run = paragraph.add_run()
    run.text = text
    run.font.size = Pt(font_size)
    run.font.color.rgb = color


def _add_metric(slide, label: str, value: str, left: float) -> None:
    shape = slide.shapes.add_shape(1, Inches(left), Inches(1.35), Inches(2.55), Inches(1.05))
    shape.fill.solid()
    shape.fill.fore_color.rgb = LIGHT_FILL
    shape.line.color.rgb = RGBColor(210, 224, 235)

    frame = shape.text_frame
    frame.clear()
    value_p = frame.paragraphs[0]
    value_p.alignment = PP_ALIGN.CENTER
    value_run = value_p.add_run()
    value_run.text = value
    value_run.font.bold = True
    value_run.font.size = Pt(24)
    value_run.font.color.rgb = ACCENT

    label_p = frame.add_paragraph()
    label_p.alignment = PP_ALIGN.CENTER
    label_run = label_p.add_run()
    label_run.text = label
    label_run.font.size = Pt(10)
    label_run.font.color.rgb = MUTED


def _add_ranked_list(slide, title: str, values: Counter[str], *, left: float, top: float) -> None:
    _add_textbox(slide, title, left=left, top=top, width=5.2, height=0.35, font_size=15, color=ACCENT)
    y = top + 0.48
    for label, count in values.most_common(5):
        _add_textbox(slide, f"{label}: {count}", left=left, top=y, width=5.2, height=0.3, font_size=12, color=TEXT)
        y += 0.38


def _add_bullet(slide, text: str, *, top: float) -> None:
    box = slide.shapes.add_textbox(Inches(1.0), Inches(top), Inches(11.4), Inches(0.55))
    frame = box.text_frame
    frame.clear()
    paragraph = frame.paragraphs[0]
    paragraph.level = 0
    run = paragraph.add_run()
    run.text = f"- {text}"
    run.font.size = Pt(16)
    run.font.color.rgb = TEXT


def _add_accent_bar(slide) -> None:
    shape = slide.shapes.add_shape(1, Inches(0), Inches(0), Inches(0.18), Inches(7.5))
    shape.fill.solid()
    shape.fill.fore_color.rgb = ACCENT
    shape.line.fill.background()


def _style_cell(cell, *, is_header: bool) -> None:
    cell.margin_left = Inches(0.07)
    cell.margin_right = Inches(0.07)
    cell.margin_top = Inches(0.04)
    cell.margin_bottom = Inches(0.04)
    if is_header:
        cell.fill.solid()
        cell.fill.fore_color.rgb = ACCENT

    for paragraph in cell.text_frame.paragraphs:
        for run in paragraph.runs:
            run.font.size = Pt(8.5 if not is_header else 9)
            run.font.bold = is_header
            run.font.color.rgb = RGBColor(255, 255, 255) if is_header else TEXT


def _top_labels(values: list[str], *, limit: int) -> list[str]:
    return [label for label, _ in Counter(values).most_common(limit)]


def _slugify(value: str) -> str:
    slug = re.sub(r"[^a-zA-Z0-9]+", "_", value.strip().lower()).strip("_")
    return slug[:80] or "physician_summary"
